<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Detalhes Viatura ID <?php echo $viatura->getId_vtr(); ?>
        </div>
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>ID:</dt>
            <dd><?php echo $viatura->getId_vtr(); ?></dd>
            <dt>Prefixo:</dt>
            <dd><?php echo $viatura->getPrefixo(); ?></dd>
            <dt>Id_Área:</dt>
            <dd><?php echo $viatura->getArea()->getDescricao(); ?></dd>
        </dl>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('viaturas', array('action' => 'editar','id' => $viatura->getId_vtr())); ?>" class="btn btn-warning btn-sm">Editar Viatura</a>
        <a href="<?php echo $this->url('viaturas'); ?>" class="btn btn-default btn-sm">Voltar</a>
    </div>
</div>