<div class="row">

    <div class="col-lg-12">

        <h1>Viaturas</h1>
        <ol class="breadcrumb">
            <li class="active"><i class="fa fa-dashboard"></i> Controle das Viaturas</li>
        </ol>

    </div>
</div>


<table class="table table-striped table-bordered table-hover">
    <thead>

    </thead>

    <tbody>
        <tr>
            <td class="text-center">ID</td>
            <td class="text-center">Prefixo</td>
            <td class="text-center">ID_Área</td>
             <td class="text-center">Ação</td>

        </tr>
        <?php foreach ($this->vtr as $viatura) : ?>
            <tr>
                <td class="text-center"><?php echo $viatura->getId_vtr(); ?></td>
                <td class="text-center"><?php echo $viatura->getPrefixo(); ?></td>
                <td class="text-center"><?php echo $viatura->getArea(); ?></td>
                    <td>
                        <a class="btn btn-xs btn-info" title="Visualizar" href="<?php echo $this->url('viaturas', array("action" => "detalhes", "id" => $viatura->getId_vtr(),)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                        <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('viaturas', array("action" => "editar", "id" => $viatura->getId_vtr(),)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                        <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('viaturas', array("action" => "deletar", "id" => $viatura->getId_vtr(),)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                    </td>

            </tr>
        <?php endforeach; ?>
    </tbody>
</table>