<?php
$estruturaColuna = function($label, $coluna_procedimento) {
    $html = '';
    $html .= "<a href='{$this->url('procedimento', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_procedimento' => $coluna_procedimento, 'coluna_sort' => ($this->coluna_procedimento!= $coluna_procedimento? 'ASC' : ($this->coluna_sort == 'DESC' ? 'ASC' : 'DESC')), 'itens_pagina' => $this->itens_pagina, 'search' => $this->search]])}'>";

    if ($this->coluna_procedimento== $coluna_procedimento) {
        $icon = $this->coluna_sort == 'ASC' ? '' : '-alt';
        $html .= "<span class='glyphicon glyphicon-sort-by-attributes{$icon}'></span> ";
    }

    $html .= $label;

    return $html;
};
?>
<tr>
    <th>
        <?php echo $estruturaColuna('Nº Registro', 'id_pro'); ?>
    </th> 
    <th>
        <?php echo $estruturaColuna('Procedimento', 'procedimento'); ?>
    </th> 
       <th>
        <?php echo $estruturaColuna('Peso', 'peso'); ?>
    </th>
    <th>Ação</th>  
</tr>
