<!--<div class="jumbotron">
    <h1>Manutenção dos dados</h1>
    <p class="lead">
        Clique no link abaixo para preenchimentos dos dados.
    </p>
</div>
-->
<br/>
<br/>
<br/>
<div class="col-lg-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-file"></i> Testes dos dados</h3>
        </div>
        <div class="panel-body">
<table class="table table-bordered table-hover table-striped tablesorter">
                    <thead>
                    </thead>

                    <tbody>
                        
                        <?php foreach ($this->dados as $oc): ?>
                            <tr>
                                <td class="text-center"><?php echo $oc->getId_oco(); ?></td>
                                <td class="text-center"><?php echo $oc->getEnd()->getRua(); ?></td>
                                <td class="text-center"><?php echo $oc->getVtr()->getPrefixo() ?></td> 
                                  <td class="text-center"><?php echo (new \DateTime($oc->getDatai()))->format('d/m/Y H:i:s'); ?></td>
                                 <td class="text-center"><?php echo (new \DateTime($oc->getDataf()))->format('d/m/Y H:i:s'); ?></td>
                                <td class="text-center"><?php echo $oc->getCiops(); ?></td>                            
                            </tr>  
                        <?php endforeach;  var_dump($this->dados)?>
                    </tbody>
                </table>  
            
    <div class="header">
        <ul class="nav nav-pills pull-left">
            <?php
            $voltar = $this->url('application', array('action' => 'index'));
            ?>
            <li <?php echo $this->menuAtivo($voltar); ?>>
                <a href="<?php echo $voltar; ?>">voltar</a>
            </li>
        </ul>
    </div>




