<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Detalhes Município ID <?php echo $municipio->getId_muni(); ?>
        </div>
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>ID:</dt>
            <dd><?php echo $municipio->getId_muni(); ?></dd>
            <dt>Município:</dt>
            <dd><?php echo $municipio->getMunicipio(); ?></dd>
        </dl>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('municipio', array('action' => 'editar','id' => $municipio->getId_muni())); ?>" class="btn btn-warning btn-sm">Editar Município</a>
        <a href="<?php echo $this->url('municipio'); ?>" class="btn btn-default btn-sm">Voltar</a>
    </div>
</div>