<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">
                    <i class="fa fa-desktop"></i> Ocorrência ID <?php echo $this->ocorrencia->getId_oco(); ?>
                    <div style="float: right;margin-top: -5px">
                        <a href="<?php //echo $this->url('ocorrencia', array('action' => 'vitimas', 'id' => $this->ocorrencia->getId_oco())); ?>" class="btn btn-success" ><i class="fa fa-user"></i> Vítimas <span class="badge"><?php echo $this->tVitimas; ?></span></a>
                        <a href="<?php //echo $this->url('ocorrencia', array('action' => 'acusados', 'id' => $this->ocorrencia->ggetId_oco())); ?>" class="btn btn-danger"><i class="fa fa-user"></i> Acusados <span class="badge"><?php echo $this->tAcusados; ?></span></a>
                        <a href="<?php// echo $this->url('ocorrencia', array('action' => 'crimes', 'id' => $this->ocorrencia->getId_oco())); ?>" class="btn btn-default"><i class="fa fa-random"></i> Crimes <span class="badge"><?php echo $this->tCrimes; ?></span></a>
                    </div>
                </div>
            </div>    
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>ID:</dt>
                    <dd><?php echo $this->ocorrencia->getId_oco(); ?></dd>
                    <dt>Rua:</dt>
                    <dd><?php echo $this->ocorrencia->getEnd()->getRua(); ?></dd>
                    <dt>Número:</dt>
             <dd><?php echo $this->ocorrencia->getEnd()->getNumero(); ?></dd>
              <dt>Bairro:</dt>
           <dd><?php echo $this->ocorrencia->getEnd()->getId_bai()->getBairro(); ?></dd>
           <dt>Município:</dt>
           <dd><?php echo $this->ocorrencia->getEnd()->getId_bai()->getMunicipio()->getMunicipio(); ?></dd>
                       <dt>Viatura:</dt>
                    <dd><?php echo $this->ocorrencia->getVtr()->getPrefixo(); ?></dd>
                          <dt>Data início:</dt>
                    <dd><?php echo (new \DateTime($this->ocorrencia->getDatai()))->format('d/m/Y H:i:s');?></dd>
                          <dt>Data fim:</dt>
                    <dd><?php echo (new \DateTime($this->ocorrencia->getDataf()))->format('d/m/Y H:i:s'); ?></dd>
                      <dt>Ciops:</dt>
                    <dd><?php echo $this->ocorrencia->getCiops(); ?></dd>
                      <dt>Narração:</dt>
                    <dd><?php echo $this->ocorrencia->getNarracao(); ?></dd>
                </dl>
            </div>
            <div class="panel-footer">
                    <a href="<?php echo $this->url('ocorrencia', array('action' => 'editar', 'id' => $this->ocorrencia->getId_oco())); ?>" class="btn btn-warning btn-sm">Editar Ocorrência</a>
                     <a href="<?php echo $this->url('ocorrencia', array('action' => 'editar', 'id' => $this->ocorrencia->getId_oco() , 'formOcorrencia' => $this->form )); ?>" class="btn btn-default">Voltar</a>
                </div>
        </div>

    </div>
</div>



