<div class="topo-table">
    <div class="row">
        <div class="col-lg-12">
            <br/>
            <h2>Ocorrências</h2>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-dashboard"></i> Controle das Ocorrências</li>
            </ol>
        </div>
    </div>


    <a href="<?php echo $this->url('ocorrencia', array('action' => 'novo')) ?>" class="btn btn-success" title="Novo"><span class="glyphicon glyphicon-plus"></span></a>

    <div class="btn-group" title="Quantidades por Página">
        <button type="button" class="btn btn-default"><?php echo $this->itens_pagina; ?></button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right" style="min-width: 75px" role="menu">
            <?php foreach (['005', '010', '025', '050', '100'] as $value): ?>
                <li class="<?php echo ($this->itens_pagina == $value ? 'active' : ''); ?>"><a href="<?php echo $this->url('ocorrencia', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_id_oco' => $coluna_id_oco, 'coluna_sort' => $this->coluna_sort, 'itens_pagina' => $value, 'search' => $this->search]]) ?>"><?php echo $value; ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>

    <form class="form-inline pull-right" role="form">
        <div class="btn-group">
            <label class="sr-only" for="localizar">Buscar...</label>
            <input type="search" name="search" value="<?php echo $this->search; ?>" class="form-control" id="localizar" placeholder="Bucar...">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
    </form>
</div>

<br />
<br />

<div class="col-lg-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-desktop"></i>  Ocorrências</h3>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped tablesorter">
                    <thead>
                        <!--pega o cabeçalho da tabela em partial/colunas_sort -->
                        <?php echo $this->partial('partial/ocorrencia/colunas_sort'); ?>
                    </thead>

                    <tbody>



                        <?php foreach ($this->ocorrencia as $i => $oc): ?>
                            <tr>

                                <td class="text-center"><?php echo $oc->getId_oco(); ?></td>
                                <!--<td class="text-center"><?php echo $oc->getEnd()->getRua(); ?></td>-->
                                <td class="text-center"><?php echo $oc->getVtr()->getPrefixo(); ?></td>
                                <td class="text-center"><?php //echo $oc->getArea()->getDescricao(); ?></td>
                                <td class="text-center"><?php echo (new \DateTime($oc->getDatai()))->format('d/m/Y'); ?></td>
                                <td class="text-center"><?php //echo $oc->getHorario(); ?></td>

                                <td>
                                    <a class="btn btn-xs btn-info" title="Visualizar" href="<?php echo $this->url('ocorrencia', array("action" => "detalhes", "id" => $oc->getId_oco(),)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                                    <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('ocorrencia', array("action" => "editar", "id" => $oc->getId_oco(),)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                                    <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('ocorrencia', array("action" => "deletar", "id" => $oc->getId_oco())); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                                </td>
                            </tr>  
                        <?php endforeach; ?>
                    </tbody>
                </table>  
            </div>
            <?php
// controle de paginação
            echo $this->paginationControl(
                    // objeto contentdo os vtr
                    $this->ocorrencia,
                    // tipo de style da paginação
                    'Sliding',
                    // partial que vai conter o html da paginação
                    [/* path */ 'partial/ocorrencia/paginator.phtml', /* modulo */ 'Application'],
                    // link rotas da paginação
                    ['route' => 'ocorrencia']
            );
            ?>
        </div>
    </div>
</div>
<div class="header">
    <ul class="nav nav-pills pull-left">
        <?php
        $voltar = $this->url('application', array('action' => 'index'));
        ?>
        <li <?php echo $this->menuAtivo($voltar); ?>>
            <a href="<?php echo $voltar; ?>">voltar</a>
        </li>
    </ul>
</div>
