<!--<div class="jumbotron">
    <h1>Manutenção dos dados</h1>
    <p class="lead">
        Clique no link abaixo para preenchimentos dos dados.
    </p>
</div>
-->
<br/>
<br/>
<br/>
<div class="col-lg-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-file"></i> Testes dos dados</h3>
        </div>
        <div class="panel-body">
            <table class="table table-bordered table-hover table-striped tablesorter">
                <thead>
                </thead>

                <tbody>
                    <?php foreach ($this->dados as $dados): ?>
                        <tr>
                            <td class="text-center">Id: <?php echo ($dados['id_ocorrencia']); ?></td>
                            <td class="text-center"> Narracao: <?php echo ($dados['narracao']); ?></td>    
                            <td class="text-center"> Data: <?php echo ($dados['datai']); ?></td>
                            <td class="text-center"> Lat: <?php echo ($dados['lat']); ?></td> 
                            <td class="text-center">Lng: <?php echo ($dados['lng']); ?></td>
                            <td class="text-center"> Rua: <?php echo ($dados['rua']); ?></td> 
                            <td class="text-center"> Numero: <?php echo ($dados['numero']); ?></td>
                        </tr>  
                    <?php endforeach; ?>
                </tbody>
            </table>  

        
            <div class="header">
                <ul class="nav nav-pills pull-left">
                    <?php
                    $voltar = $this->url('application', array('action' => 'index'));
                    ?>
                    <li <?php echo $this->menuAtivo($voltar); ?>>
                        <a href="<?php echo $voltar; ?>">voltar</a>
                    </li>
                </ul>
            </div>

     </div>


