<br/>
<br/>
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Add dados  veículo/lesão/homicídio da ocorrência ID: <?php echo $this->id ?>       
        </div>
    </div>

    <br>
    <div class="alert alert-info" role="alert">Dados do veículo</div> 
    <?php
    // objeto form veículo
    $form = $this->formV;
    $form->prepare();
    // configurar url formulário
    $form->setAttribute('action', $this->url('ocorrencia', array('action' => 'adicionarVAH')));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($form) ?>
    <div class="panel-body">
        <div class="form-group">
            <label for="inputQuantidadeV" class="col-lg-3 col-md-3 control-label">Quantidade*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($form->get('qtdeV'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('qtdeV'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputDescricaoV" class="col-lg-3 col-md-3 control-label">Descrição*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($form->get('descricaoV'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('descricaoV'));
                ?>
            </div>
        </div>

    </div>

    <br>
    <div class="alert alert-info" role="alert">Dados da arma</div>

    <?php
    $formA = $this->formA;
    $formA->prepare();
    // configurar url formulário
    //$formA->setAttribute('action', $this->url('ocorrencia', array('action' => 'atualizarLesao', 'id' => $this->id)));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto  ?>
    <?php
    echo $this->form()->openTag($formA);
    ?>
    <div class="panel-body">
       <div class="form-group">
            <label for="inputQuantidade" class="col-lg-3 col-md-3 control-label">Quantidade*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formA->get('qtdeA'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formA->get('qtdeA'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputTipo" class="col-lg-3 col-md-3 control-label">Descrição*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formA->get('descricaoA'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formA->get('descricaoA'));
                ?>
            </div>
        </div>
 </div>
        <br>   
       <div class="alert alert-info" role="alert">Dados do homicídio</div>
        <?php
        // objeto form contato
        $formH = $this->formH;
        $formH->prepare();
        // configurar url formulário
        //$formH->setAttribute('action', $this->url('ocorrencia', array('action' => 'adicionarALH', 'id' => $this->id)));
        ?>

        <?php // renderiza html <form> com atributos configurados no objeto ?>
        <?php echo $this->form()->openTag($formH); ?>
        <div class="panel-body">


            <div class="form-group">
                <label for="inputQuantidade" class="col-lg-3 col-md-3 control-label">Quantidade*:</label>
                <div class="col-lg-9  col-md-9">
                    <?php
// renderiza html input
                    echo $this->formInput($formH->get('qtde'));

// renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formH->get('qtde'));
                    ?>
                </div>
            </div>

            <div class="form-group">
                <label for="inputTipo" class="col-lg-3 col-md-3 control-label">Tipo*:</label>
                <div class="col-lg-9  col-md-9">
                    <?php
// renderiza html input
                    echo $this->formInput($formH->get('tipo_homi'));
// renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formH->get('tipo_homi'));
                    ?>
                </div>
            </div>
            <div class="form-group">
                <label for="inputPresidio" class="col-lg-3 col-md-3 control-label">Presídio?*:</label>
                <div class="col-lg-9  col-md-9">
                    <div class="checkbox">
                        <?php
// renderiza html input
                        echo $this->formRadio($formH->get('presidio'));
// renderiza elemento de erro
                        echo $this->formElementErrors()
                                ->setMessageOpenFormat('<small class="text-danger">')
                                ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                                ->setMessageCloseString('</small>')
                                ->render($formH->get('presidio'));
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="panel-footer">

        <?php
// renderiza html input hidden para id
        echo $this->formHidden($formV->get('id'));
        ?>

        <button type="submit" class="btn btn-primary">Atualizar Dados</button>
        <!--<a href="<?php //echo $this->url('ocorrencia');   ?>" class="btn btn-default">Voltar</a>-->
    </div>

    <?php // renderiza html </form>  ?>
    <?php echo $this->form()->closeTag() ?>
</div>