
<script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
async></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=true"></script>
 
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">

                <div class="panel-titNovale">
                    <i class="fa fa-map-marker"></i> Localização dos crimes                  
                    <div style="float: right;margin-top: -5px">

               <!--  <a href="/ocorrencia_beta/public/ocorrencia/vitimas/0" class="btn btn-success" ><i class="fa fa-user"></i> Vítimas <span class="badge">1</span></a>
                <a href="/ocorrencia_beta/public/acusado/novo" class="btn btn-danger"><i class="fa fa-user"></i> Acusados <span class="badge">1</span></a>
                        -->
                    </div>
                </div>
            </div>
            <?php
            // objeto form ocorrencia
            $formRelarorio = $this->formRelarorio;
            // preparar elementos do formulário
            $formRelarorio->prepare();
            // configurar url formulário
            //$formRelarorio->setAttribute('action', $this->url('ocorrencia', ['action' => 'mapacrime']));
            ?>
            <?php // renderiza html <form> com atributos configurados no objeto ?>
            <?php echo $this->form()->openTag($formRelarorio) ?>
     
            <div class="panel-body">

                <div id="ponto-mapa">

                </div>
     
                <label for="inputCrimes" class="col-lg-3 col-md-3">Crime*:</label>
                <div class="col-lg-3  col-md-3">
                    <?php
                    // renderiza html input
                    echo $this->formSelect($formRelarorio->get('id_crimeR'));
                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formRelarorio->get('id_crimeR'));
                    ?>
                    <br>
                </div>

                <label for="inputDataI" class="col-lg-3 col-md-3 ">Data/hora Início*:</label>
                <div class="col-lg-3  col-md-3">
                    <div class='input-group date' id='datetimepickerF'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($formRelarorio->get('datai'));
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                                ->setMessageOpenFormat('<small class="text-danger">')
                                ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                                ->setMessageCloseString('</small>')
                                ->render($formRelarorio->get('datai'));
                        ?>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    <br>
                </div>

                <label for="inputDataF" class="col-lg-3 col-md-3 ">Data/hora Fim*:</label>
                <div class="col-lg-3  col-md-3">
                    <div class='input-group date' id='datetimepickerI'>
                        <?php
                        // renderiza html input
                        echo $this->formInput($formRelarorio->get('dataf'));
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                                ->setMessageOpenFormat('<small class="text-danger">')
                                ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                                ->setMessageCloseString('</small>')
                                ->render($formRelarorio->get('dataf'));
                        ?>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    <br>
                </div>

                <label for="inputMunicipio" class="col-lg-3 col-md-3">Município*:</label>
                <div class="col-lg-3  col-md-3">
                    <?php
                    // renderiza html input
                    echo $this->formSelect($formRelarorio->get('id_muniO'));
                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formRelarorio->get('id_muniO'));
                    ?>
                    <br>
                </div>

          

                <label for="inputBairro" class="col-lg-3 col-md-3 ">Pontos*:</label>     
                <div class="col-lg-3  col-md-3">
                    <?php
                    // renderiza html input
                    echo $this->formSelect($formRelarorio->get('pontos'));
                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formRelarorio->get('pontos'));
                    ?>
                    <br>
                    <button type="button" id="remove" class="btn btn-primary fa fa-map-marker "> Remove</button>
                </div>
                
            </div>
            
        </div>
    </div>
</div>




<div class="panel-footer">

    <a href="<?php echo $this->url('relatorios'); ?>" class="btn btn-default">Voltar</a>
</div>
<?php // renderiza html </form>  ?>
<?php echo $this->form()->closeTag() ?>





