<?php
$estruturaColuna = function($label, $coluna_municipio) {
    $html = '';
    $html .= "<a href='{$this->url('municipio', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_municipio' => $coluna_municipio, 'coluna_sort' => ($this->coluna_municipio!= $coluna_municipio? 'ASC' : ($this->coluna_sort == 'DESC' ? 'ASC' : 'DESC')), 'itens_pagina' => $this->itens_pagina, 'search' => $this->search]])}'>";

    if ($this->coluna_municipio== $coluna_municipio) {
        $icon = $this->coluna_sort == 'ASC' ? '' : '-alt';
        $html .= "<span class='glyphicon glyphicon-sort-by-attributes{$icon}'></span> ";
    }

    $html .= $label;

    return $html;
};
?>
<tr>
    <th>
        <?php echo $estruturaColuna('Nº Registro', 'id_muni'); ?>
    </th> 
    <th>
        <?php echo $estruturaColuna('Município', 'municipio'); ?>
    </th> 
    <th>Ação</th>  
</tr>
