<?php
$estruturaColuna = function($label, $coluna_descricao) {
    $html = '';
    $html .= "<a href='{$this->url('area', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_descricao' => $coluna_descricao, 'coluna_sort' => ($this->coluna_descricao!= $coluna_descricao? 'ASC' : ($this->coluna_sort == 'DESC' ? 'ASC' : 'DESC')), 'itens_pagina' => $this->itens_pagina, 'search' => $this->search]])}'>";

    if ($this->coluna_descricao == $coluna_descricao) {
        $icon = $this->coluna_sort == 'ASC' ? '' : '-alt';
        $html .= "<span class='glyphicon glyphicon-sort-by-attributes{$icon}'></span> ";
    }

    $html .= $label;

    return $html;
};
?>
<tr>
    <th>
        <?php echo $estruturaColuna('Nº Registro', 'id_area'); ?>
    </th>
    <th>
        <?php echo $estruturaColuna('Área', 'descricao'); ?>
    </th> 
    <th>
        <?php echo $estruturaColuna('Município', 'municipio'); ?>
    </th> 
    <th>Ação</th>  
</tr>
