<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Editar Área ID:  <?php echo $this->id ?>  
        </div>
    </div>
    
    <?php
    // objeto form contato
     $formArea = $this->formArea;
       //var_dump ($formViatura);
    // preparar elementos do formulário
    $formArea->prepare();
    // configurar url formulário
    $formArea->setAttribute('action', $this->url('area', ['action' => 'atualizar']));
    ?>  
    
    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formArea) ?>
    
    <div class="panel-body">
        <div class="form-group">
            <label for="descricao" class="col-lg-3 col-md-3 control-label">Descrição*:</label>
            <div class="col-lg-9 col-md-9">
                <?php 
                // renderiza html input
                echo $this->formInput($formArea->get('descricao'));
                
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formArea->get('descricao'));
                ?>
            </div>
        </div>
 
        <div class="form-group">
            <label for="id_descricao" class="col-lg-3 col-md-3 control-label">Município*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formSelect($formArea->get('id_muni'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formArea->get('id_muni'));
                ?>
            </div>
        </div>
 
    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($formArea->get('id_area')); 
        ?>
 
        <button type="submit" class="btn btn-primary">Atualizar Área</button>
        <a href="<?php echo $this->url('area'); ?>" class="btn btn-default">Voltar</a>
    </div>
 
    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>