<div class="jumbotron">
    <h1>Manutenção dos dados</h1>
    <p class="lead">
        Clique no link abaixo para preenchimentos dos dados.
    </p>
   
    <a href="<?php echo $this->url('area', array('action' => 'index')); ?>"><i class="fa fa-road"></i> Áreas</a><br>
    <a href="<?php echo $this->url('bairro', array('action' => 'index')); ?>"><i class="fa fa-road"></i> Bairros</a><br>
    <a href="<?php echo $this->url('municipio', array('action' => 'index')); ?>"><i class="fa fa-road"></i> Municípios</a><br>
    <a href="<?php echo $this->url('viaturas', array('action' => 'index')); ?>"><i class="fa fa-road"></i> Viaturas</a><br>
     <a href="<?php echo $this->url('graduacao', array('action' => 'index')); ?>"><i class="fa fa-road"></i> Graduações</a><br>
     <a href="<?php echo $this->url('crime', array('action' => 'index')); ?>"><i class="fa fa-road"></i> Crimes</a><br>
     <a href="<?php echo $this->url('procedimento', array('action' => 'index')); ?>"><i class="fa fa-road"></i> Procedimentos</a><br>
     <a href="<?php echo $this->url('droga', array('action' => 'index')); ?>"><i class="fa fa-road"></i> Drogas</a><br>
     <a href="<?php echo $this->url('arma', array('action' => 'index')); ?>"><i class="fa fa-road"></i> Armas</a><br>
     <a href="<?php echo $this->url('policiais', array('action' => 'index')); ?>"><i class="fa fa-road"></i> Policiais</a><br>

</div>