<?php
$estruturaColuna = function($label, $coluna_droga) {
    $html = '';
    $html .= "<a href='{$this->url('droga', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_droga' => $coluna_droga, 'coluna_sort' => ($this->coluna_droga!= $coluna_droga? 'ASC' : ($this->coluna_sort == 'DESC' ? 'ASC' : 'DESC')), 'itens_pagina' => $this->itens_pagina, 'search' => $this->search]])}'>";

    if ($this->coluna_droga== $coluna_droga) {
        $icon = $this->coluna_sort == 'ASC' ? '' : '-alt';
        $html .= "<span class='glyphicon glyphicon-sort-by-attributes{$icon}'></span> ";
    }

    $html .= $label;

    return $html;
};
?>
<tr>
    <th>
        <?php echo $estruturaColuna('Nº Registro', 'id_droga'); ?>
    </th> 
    <th>
        <?php echo $estruturaColuna('Droga', 'droga'); ?>
    </th> 
    <th>Ação</th>  
</tr>
