<br/>
<br/>
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Nova Graduação
        </div>
    </div>

    <?php
    // objeto form contato
    $formGraduacao = $this->formGraduacao;
    // preparar elementos do formulário
    $formGraduacao->prepare();
    // configurar url formulário
    $formGraduacao->setAttribute('action', $this->url('graduacao', array('action' => 'adicionar')));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formGraduacao) ?>
    <div class="panel-body">


        <div class="form-group">
            <label for="inputSigla" class="col-lg-3 col-md-3 control-label">Sigla*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formGraduacao->get('sigla'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formGraduacao->get('sigla'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputGraduacao" class="col-lg-3 col-md-3 control-label">Graduação*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formGraduacao->get('graduacao'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formGraduacao->get('graduacao'));
                ?>
            </div>
        </div>


    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($formGraduacao->get('id_grad'));
        ?>

        <button type="submit" class="btn btn-primary">Salvar Graduação</button>
        <a href="<?php echo $this->url('graduacao'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php // renderiza html </form>  ?>
    <?php echo $this->form()->closeTag() ?>
</div>