

<?php
$estruturaColuna = function($label, $coluna_datai) {
    $html = '';
    $html .= "<a href='{$this->url('ocorrencia', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna__datai' => $coluna_datai, 'coluna_sort' => ($this->coluna__datai!= $coluna_datai? 'ASC' : ($this->coluna_sort == 'DESC' ? 'ASC' : 'DESC')), 'itens_pagina' => $this->itens_pagina, 'search' => $this->search]])}'>";

    if ($this->coluna_datai == $coluna_datai) {
        $icon = $this->coluna_sort == 'ASC' ? '' : '-alt';
        $html .= "<span class='glyphicon glyphicon-sort-by-attributes{$icon}'></span> ";
    }

    $html .= $label;

    return $html;
};
?>
<tr>
   
   <th class="header" style="width: 13%;">
        <?php echo $estruturaColuna('Nº Registro', 'id_ocorrencia'); ?>
    </th> 
    <th>
        <?php echo $estruturaColuna('Rua', 'rua'); ?>
    </th> 
    <th>
        <?php echo $estruturaColuna('Viatura', 'prefixo'); ?>
    </th> 
    <th>
        <?php echo $estruturaColuna('Data/hora início', 'datai'); ?>
    </th>
     <th>
        <?php echo $estruturaColuna('Data/hora fim', 'dataf'); ?>
    </th>
     <th>
        <?php echo $estruturaColuna('CIOPS', 'ciops'); ?>
    </th>
    <th class="header" style="width: 10%;text-align: center">Ação</th>  
</tr>
