<?php
$estruturaColuna = function($label, $coluna_silga) {
    $html = '';
    $html .= "<a href='{$this->url('graduacao', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_silga' => $coluna_silga, 'coluna_sort' => ($this->coluna_silga!= $coluna_silga? 'ASC' : ($this->coluna_sort == 'DESC' ? 'ASC' : 'DESC')), 'itens_pagina' => $this->itens_pagina, 'search' => $this->search]])}'>";

    if ($this->coluna_silga== $coluna_silga) {
        $icon = $this->coluna_sort == 'ASC' ? '' : '-alt';
        $html .= "<span class='glyphicon glyphicon-sort-by-attributes{$icon}'></span> ";
    }

    $html .= $label;

    return $html;
};
?>
<tr>
    <th>
        <?php echo $estruturaColuna('Nº Registro', 'id_grad'); ?>
    </th> 
    <th>
        <?php echo $estruturaColuna('Sigla', 'sigla'); ?>
    </th> 
       <th>
        <?php echo $estruturaColuna('Graduação', 'graduacao'); ?>
    </th>
    <th>Ação</th>  
</tr>
