
<div class="topo-table">
    <div class="row">
        <div class="col-lg-12">
            <br/>
            <h2>Acusado</h2>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-dashboard"></i> Controle dos Acusados</li>
            </ol>
        </div>
    </div>
    <a href="<?php echo $this->url('acusados', array('action' => 'novo')) ?>" class="btn btn-success" title="Novo"><span class="glyphicon glyphicon-plus"></span></a>
    <div class="btn-group" title="Quantidades por Página">
        <button type="button" class="btn btn-default"><?php echo $this->itens_pagina; ?></button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right" style="min-width: 75px" role="menu">
            <?php foreach (['005', '010', '025', '050', '100'] as $value): ?>
                <li class="<?php echo ($this->itens_pagina == $value ? 'active' : ''); ?>"><a href="<?php echo $this->url('acusados', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_nome' => $coluna_nome, 'coluna_sort' => $this->coluna_sort, 'itens_pagina' => $value, 'search' => $this->search]]) ?>"><?php echo $value; ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <form class="form-inline pull-right" role="search">
        <div class="btn-group">
            <label class="sr-only" for="localizar">Buscar...</label>
            <input type="text" name="search" value="<?php echo $this->search; ?>" class="form-control" id="localizar" placeholder="Bucar..." >
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
    </form>
</div>

<br />
<br />

<div class="col-lg-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="glyphicon glyphicon-user"></i> Vitimas</h3>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped tablesorter">
                    <thead>
                        <!--pega o cabeçalho da tabela em partial/colunas_sort -->
                        <?php echo $this->partial('partial/acusado/colunas_sort'); ?>
                    </thead>
                    <tbody>
                        <?php foreach ($this->acusado as $i => $acusado): ?>
                            <tr>
                                <td class="text-center"><?php echo $acusado->getId_acusado(); ?></td>
                                <td class="text-center"><?php echo $acusado->getNome() ?></td>
                                <td class="text-center"><?php echo $acusado->getTelefone(); ?></td>
                                <td class="text-center"><?php echo (new \DateTime($acusado->getData_Nasc()))->format('d/m/Y H:i:s'); ?></td>
                                <td class="text-center"><?php echo $acusado->getSexo(); ?></td>
                                <td class="text-center"><?php echo $acusado->getCaracteristicas(); ?></td>
                                <td class="text-center"><?php echo $acusado->getGenitora(); ?></td>
                                <td class="text-center"><?php echo $acusado->getEnd()->getRua(); ?></td>
                                <td class="text-center"><?php echo $acusado->getEnd()->getNumero(); ?></td>       
                               <td class="text-center"><?php echo $acusado->getEnd()->getId_bai()->getBairro(); ?></td>
                               <td class="text-center"><?php echo $acusado->getEnd()->getId_bai()->getMunicipio()->getMunicipio(); ?></td>
                                <td>
                                    <a class="btn btn-xs btn-info" title="Visualizar" href="<?php echo $this->url('acusados', array("action" => "detalhes", "id" => $acusado->getId_acusado(),)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                                    <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('acusados', array("action" => "editar", "id" => $acusado->getId_acusado(),)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                                    <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('acusados', array("action" => "deletar", "id" => $acusado->getId_acusado())); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                                </td>
                            </tr>  
                        <?php endforeach; ?>
                    </tbody>
                </table>

            </div>
            <?php
// controle de paginação
            echo $this->paginationControl(
                    // objeto contentdo os vtr
                    $this->acusado,
                    // tipo de style da paginação
                    'Sliding',
                    // partial que vai conter o html da paginação
                    [/* path */ 'partial/acusado/paginator.phtml', /* modulo */ 'Application'],
                    // link rotas da paginação
                    ['route' => 'acusados']
            );
            ?>
        </div>
    </div>
</div>
<div class="header">
    <ul class="nav nav-pills pull-left">
        <?php
        $voltar = $this->url('config');
        ?>
        <li <?php echo $this->menuAtivo($voltar); ?>>
            <a href="<?php echo $voltar; ?>">voltar</a>
        </li>
    </ul>
</div>