<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Editar Droga ID:  <?php echo $this->id ?>  
        </div>
    </div>
    
    <?php
    // objeto form contato
     $formDroga = $this->formDroga;
       //var_dump ($formViatura);
    // preparar elementos do formulário
    $formDroga->prepare();
    // configurar url formulário
    $formDroga->setAttribute('action', $this->url('droga', ['action' => 'atualizar']));
    ?>  
    
    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formDroga) ?>
    
    <div class="panel-body">
        <div class="form-group">
            <label for="droga" class="col-lg-3 col-md-3 control-label">Droga*:</label>
            <div class="col-lg-9 col-md-9">
                <?php 
                // renderiza html input
                echo $this->formInput($formDroga->get('droga'));
       
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formDroga->get('droga'));
                ?>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($formDroga->get('id_droga')); 
        ?>
 
        <button type="submit" class="btn btn-primary">Atualizar Droga</button>
        <a href="<?php echo $this->url('droga'); ?>" class="btn btn-default">Voltar</a>
    </div>
 
    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>














