<div class="topo-table">
    <div class="row">
        <div class="col-lg-12">
            <br/>
            <h2>Drogas</h2>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-dashboard"></i> Controle das Drogas</li>
            </ol>
        </div>
    </div>
    <a href="<?php echo $this->url('droga', array('action' => 'novo')) ?>" class="btn btn-success" title="Novo"><span class="glyphicon glyphicon-plus"></span></a>
    <div class="btn-group" title="Quantidades por Página">
        <button type="button" class="btn btn-default"><?php echo $this->itens_pagina; ?></button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right" style="min-width: 75px" role="menu">
            <?php foreach (['005', '010', '025', '050', '100'] as $value): ?>
                <li class="<?php echo ($this->itens_pagina == $value ? 'active' : ''); ?>"><a href="<?php echo $this->url('droga', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_droga' => $coluna_droga, 'coluna_sort' => $this->coluna_sort, 'itens_pagina' => $value, 'search' => $this->search]]) ?>"><?php echo $value; ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <form class="form-inline pull-right" role="form">
        <div class="btn-group">
            <label class="sr-only" for="localizar">Buscar...</label>
            <input type="search" name="search" value="<?php echo $this->search; ?>" class="form-control" id="localizar" placeholder="Bucar...">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
    </form>
</div>

<br />
<br />
<div class="col-lg-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="glyphicon glyphicon-leaf"></i> Drogas</h3>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped tablesorter">
                    <div class="corpo-table">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <!--pega o cabeçalho da tabela em partial/colunas_sort -->
                                <?php echo $this->partial('partial/droga/colunas_sort'); ?>
                            </thead>
                            <tbody>
                                <?php foreach ($this->droga as $i => $droga): ?>
                                    <tr>
                                        <td class="text-center"><?php echo $droga->getId_droga(); ?></td>
                                        <td class="text-center"><?php echo $droga->getDroga(); ?></td>
                                        <td>
                                            <a class="btn btn-xs btn-info" title="Visualizar" href="<?php echo $this->url('droga', array("action" => "detalhes", "id" => $droga->getId_droga(),)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                                            <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('droga', array("action" => "editar", "id" => $droga->getId_droga(),)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                                            <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('droga', array("action" => "deletar", "id" => $droga->getId_droga())); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                                        </td>
                                    </tr>  
                                <?php endforeach; ?>
                            </tbody>
                        </table>

                    </div>
                    <?php
// controle de paginação
                    echo $this->paginationControl(
                            // objeto contentdo os vtr
                            $this->droga,
                            // tipo de style da paginação
                            'Sliding',
                            // partial que vai conter o html da paginação
                            [/* path */ 'partial/droga/paginator.phtml', /* modulo */ 'Application'],
                            // link rotas da paginação
                            ['route' => 'droga']
                    );
                    ?>
            </div>
        </div>

        <div class="header">
            <ul class="nav nav-pills pull-left">
                <?php
                $voltar = $this->url('config');
                ?>
                <li <?php echo $this->menuAtivo($voltar); ?>>
                    <a href="<?php echo $voltar; ?>">voltar</a>
                </li>
            </ul>
        </div>