<br/>
<br/>
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Nova Vítima          
        </div>
    </div>
    <?php
    // objeto form contato
    $formVitima = $this->formVitima;
    // preparar elementos do formulário
    $formVitima->prepare();
    // configurar url formulário
    $formVitima->setAttribute('action', $this->url('vitimas', array('action' => 'adicionar')));
    ?>
    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formVitima) ?>
    <div class="panel-body">
        <div class="form-group">
            <label for="inputIdGrad" class="col-lg-3 col-md-3 control-label">Nome*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formVitima->get('nome'));
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formVitima->get('nome'));
                ?>
            </div>

        </div>

        <div class="form-group">
            <label for="inputDecricao" class="col-lg-3 col-md-3 control-label">Telefone*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formVitima->get('telefone'));
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formVitima->get('telefone'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputDataV" class="col-lg-3 col-md-3 control-label">Data Nascimento*:</label>
            <div class="col-lg-3  col-md-3">
                <div class='input-group date' id='datetimepickerNascV'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formVitima->get('data_nasc'));
                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formVitima->get('data_nasc'));
                    ?>

                    <span class="input-group-addon add-on"><span class="glyphicon glyphicon-calendar"></span></span>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="inputSexo" class="col-lg-3 col-md-3 control-label">Sexo*:</label>
            <div class="col-lg-9  col-md-9">
                <div class="checkbox">
                    <?php
                    // renderiza html input
                    echo $this->formRadio($formVitima->get('sexo'));
                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                            ->setMessageOpenFormat('<small class="text-danger">')
                            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                            ->setMessageCloseString('</small>')
                            ->render($formVitima->get('sexo'));
                    ?>
                </div>
            </div>
        </div>

             <div class="form-group">
            <label for="inputRua" class="col-lg-3 col-md-3 control-label">Rua*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formVitima->get('rua'));
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formVitima->get('rua'));
                ?>
            </div>
        </div>


        <div class="form-group">
            <label for="inputNumero" class="col-lg-3 col-md-3 control-label">Numero*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formVitima->get('numero'));
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formVitima->get('numero'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputMunicipio" class="col-lg-3 col-md-3 control-label">Município*:</label>
            <div class="col-lg-3  col-md-3">
                <?php
                // renderiza html input
                echo $this->formSelect($formVitima->get('id_muniO'));
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formVitima->get('id_muniO'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputBairro" class="col-lg-3 col-md-3 control-label">Bairro*:</label>
            <div class="col-lg-3  col-md-3">
                <?php
                // renderiza html input
                echo $this->formSelect($formVitima->get('id_bai'));
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formVitima->get('id_bai'));
                ?>
            </div>
        </div>
    </div>
</div>

<div class="panel-footer">
    <?php
    // renderiza html input hidden para id
    echo $this->formHidden($formVitima->get('id_vitima'));
    ?>

    <button type="submit" class="btn btn-primary">Salvar Vitima</button>
    <a href="<?php echo $this->url('vitimas'); ?>" class="btn btn-default">Voltar</a>
</div>

<?php // renderiza html </form>  ?>
<?php echo $this->form()->closeTag() ?>
