<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Detalhes Procedimento ID <?php echo $procedimento->getId_pro(); ?>
        </div>
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>ID:</dt>
            <dd><?php echo $procedimento->getId_pro(); ?></dd>
            <dt>Procedimento:</dt>
            <dd><?php echo $procedimento->getProcedimento(); ?></dd>
            <dt>Peso:</dt>
            <dd><?php echo $procedimento->getPeso(); ?></dd>
        </dl>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('procedimento', array('action' => 'editar','id' => $procedimento->getId_pro())); ?>" class="btn btn-warning btn-sm">Editar Procedimento</a>
        <a href="<?php echo $this->url('procedimento'); ?>" class="btn btn-default btn-sm">Voltar</a>
    </div>
</div>