<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Editar Procedimento ID:  <?php echo $this->id ?>  
        </div>
    </div>
    
    <?php
    // objeto form contato
     $formProcedimento = $this->formProcedimento;
       //var_dump ($formViatura);
    // preparar elementos do formulário
    $formProcedimento->prepare();
    // configurar url formulário
    $formProcedimento->setAttribute('action', $this->url('procedimento', ['action' => 'atualizar']));
    ?>  
    
    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formProcedimento) ?>
    
    <div class="panel-body">
         <div class="form-group">
            <label for="inputSigla" class="col-lg-3 col-md-3 control-label">Procedimento*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formProcedimento->get('procedimento'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formProcedimento->get('procedimento'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputProcedimento" class="col-lg-3 col-md-3 control-label">Peso*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formProcedimento->get('peso'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formProcedimento->get('peso'));
                ?>
            </div>
        </div>


    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($formProcedimento->get('id_pro')); 
        ?>
 
        <button type="submit" class="btn btn-primary">Atualizar Procedimento</button>
        <a href="<?php echo $this->url('procedimento'); ?>" class="btn btn-default">Voltar</a>
    </div>
 
    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>














