<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Editar Bairro ID:  <?php echo $this->id ?>  
        </div>
    </div>
    
    <?php
    // objeto form bairro
     $formBairro = $this->formBairro;
       //var_dump ($formViatura);
    // preparar elementos do formulário
    $formBairro->prepare();
    // configurar url formulário
    $formBairro->setAttribute('action', $this->url('bairro', ['action' => 'atualizar']));
    ?>  
    
    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formBairro) ?>
    
    <div class="panel-body">
        <div class="form-group">
            <label for="bairro" class="col-lg-3 col-md-3 control-label">Bairro*:</label>
            <div class="col-lg-9 col-md-9">
                <?php 
                // renderiza html input
                echo $this->formInput($formBairro->get('bairro'));
                
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formBairro->get('bairro'));
                ?>
            </div>
        </div>
 
        <div class="form-group">
            <label for="id_municipio" class="col-lg-3 col-md-3 control-label">Municipio*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formSelect($formBairro->get('id_muni'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formBairro->get('id_muni'));
                ?>
            </div>
        </div>
             <div class="form-group">
            <label for="id_area" class="col-lg-3 col-md-3 control-label">Area*:</label>
            <div class="col-lg-9  col-md-9">
                <?php
                // renderiza html input
                echo $this->formSelect($formBairro->get('id_area'));
                
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formBairro->get('id_area'));
                ?>
            </div>
        </div>
 
    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($formBairro->get('id_bai')); 
        ?>
 
        <button type="submit" class="btn btn-primary">Atualizar Bairro</button>
        <a href="<?php echo $this->url('bairro'); ?>" class="btn btn-default">Voltar</a>
    </div>
 
    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>