
<div class="topo-table">
<div class="row">

    <div class="col-lg-12">

        <h1>Bairro</h1>
        <ol class="breadcrumb">
            <li class="active"><i class="fa fa-dashboard"></i> Controle dos Bairros</li>
        </ol>

    </div>
</div>

    <a href="<?php echo $this->url('bairro', array('action' => 'novo')) ?>" class="btn btn-success" title="Novo"><span class="glyphicon glyphicon-plus"></span></a>

    <div class="btn-group" title="Quantidades por Página">
        <button type="button" class="btn btn-default"><?php echo $this->itens_pagina; ?></button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right" style="min-width: 75px" role="menu">
            <?php foreach (['005', '010', '025', '050', '100'] as $value): ?>
                <li class="<?php echo ($this->itens_pagina == $value ? 'active' : ''); ?>"><a href="<?php echo $this->url('bairro', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_bairro' => $coluna_bairro, 'coluna_sort' => $this->coluna_sort, 'itens_pagina' => $value, 'search' => $this->search]]) ?>"><?php echo $value; ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>

    <form class="form-inline pull-right" role="form">
        <div class="form-group">
            <label class="sr-only" for="localizar">Buscar...</label>
            <input type="search" name="search" value="<?php echo $this->search; ?>" class="form-control" id="localizar" placeholder="Bucar...">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
    </form>
</div>

<br />

<div class="corpo-table">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <!--pega o cabeçalho da tabela em partial/colunas_sort -->
            <?php echo $this->partial('partial/bairro/colunas_sort'); ?>
        </thead>

        <tbody>
            
       
            
            <?php foreach ($this->bairro as $i=>$bairro): ?>
            <tr>

                    <td class="text-center"><?php echo $bairro->getId_bai(); ?></td>
                    <td class="text-center"><?php echo $bairro->getBairro(); ?></td>
                    <td class="text-center"><?php echo $bairro->getArea()->getDescricao()?></td>
                    <td class="text-center"><?php echo $bairro->getMunicipio()->getMunicipio()?></td>
                  
                    <td>
                        <a class="btn btn-xs btn-info" title="Visualizar" href="<?php echo $this->url('bairro', array("action" => "detalhes", "id" => $bairro->getId_bai(),)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                        <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('bairro', array("action" => "editar", "id" => $bairro->getId_bai(),)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                        <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('bairro', array("action" => "deletar", "id" => $bairro->getId_bai())); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                    </td>
                </tr>  
            <?php endforeach; ?>
                
        </tbody>
    </table>
    
    <?php
// controle de paginação
    echo $this->paginationControl(
            // objeto contentdo os vtr
            $this->bairro,
            // tipo de style da paginação
            'Sliding',
            // partial que vai conter o html da paginação
            [/* path */ 'partial/bairro/paginator.phtml', /* modulo */ 'Application'],
            // link rotas da paginação
            ['route' => 'bairro']
    );
    ?>
</div>