<br/>
<br/>
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Novo Bairro         
        </div>
    </div>

    <?php
    // objeto form bairro
    $formBairro = $this->formBairro;
    // preparar elementos do formulário
    $formBairro->prepare();
    // configurar url formulário
    $formBairro->setAttribute('action', $this->url('bairro', array('action' => 'adicionar')));
    ?>
    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formBairro) ?>
    <div class="panel-body">
        <div class="form-group">
            <label for="inputBairro" class="col-lg-3 col-md-3 control-label">Bairro*:</label>
            <div class="col-lg-2  col-md-2">
                <?php
                // renderiza html input
                echo $this->formInput($formBairro->get('bairro'));
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formBairro->get('bairro'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputIdmuni" class="col-lg-3 col-md-3 control-label">Município*:</label>
             <div class="col-lg-2  col-md-2">
                <?php
                // renderiza html input
                echo $this->formSelect($formBairro->get('id_muni'));
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formBairro->get('id_muni'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputIdmuni" class="col-lg-3 col-md-3 control-label">Área*:</label>
             <div class="col-lg-2  col-md-2">
                <?php
                // renderiza html input
                echo $this->formSelect($formBairro->get('id_area'));
                // renderiza elemento de erro
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formBairro->get('id_area'));
                ?>
            </div>
        </div>

    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($formBairro->get('id_bai'));
        ?>
        <button type="submit" class="btn btn-primary">Salvar Bairro</button>
        <a href="<?php echo $this->url('bairro'); ?>" class="btn btn-default">Voltar</a>
    </div>
    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>