 

<div class="row">
    <div class="col-lg-12">
        <br/>
        <h2>Estatísticas</h2>
        <ol class="breadcrumb">
            <li class="active"><i class="fa fa-dashboard"></i> SGO</li>
        </ol>
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Os dados de ocorrências criminais são informações valiosas que precisam ser armazenadas e tratadas de forma estruturada para serem utilizadas como ferramenta de prevenção de crimes. Estas informações possuem grande relevância social, portanto precisam ser manipuladas com alta precisão para gerar estatísticas confiáveis. 
        </div>
    </div>
</div><!-- /.row -->

<?php
// objeto form ocorrencia
$formRelarorio = $this->formRelarorio;
// preparar elementos do formulário
$formRelarorio->prepare();
// configurar url formulário
//$formRelarorio->setAttribute('action', $this->url('ocorrencia', ['action' => 'mapacrime']));
?>
<?php // renderiza html <form> com atributos configurados no objeto ?>
<?php echo $this->form()->openTag($formRelarorio) ?>

<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-6">
                        <i class="fa fa-comments fa-5x"></i>
                    </div>
                    <div class="col-xs-6 text-right homicidio">
                        <p class="announcement-text">Homicídios</p>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer announcement-bottom">
                    <div class="row">
                        <div class="col-xs-6">
                            View Mentions
                        </div>
                        <div class="col-xs-6 text-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-6">
                        <i class="fa fa-check fa-5x"></i>
                    </div>
                    <div class="col-xs-6 text-right lesao">
                        <p class="announcement-text">Lesões</p>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer announcement-bottom">
                    <div class="row">
                        <div class="col-xs-6">
                            Complete Tasks
                        </div>
                        <div class="col-xs-6 text-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-6">
                        <i class="fa fa-tasks fa-5x"></i>
                    </div>
                    <div class="col-xs-6 text-right arma">
                        <p class="announcement-text">Armas</p>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer announcement-bottom">
                    <div class="row">
                        <div class="col-xs-6">
                            Fix Issues
                        </div>
                        <div class="col-xs-6 text-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="panel panel-success">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-6">
                        <i class="fa fa-comments fa-5x"></i>
                    </div>
                    <div class="col-xs-6 text-right entorpecente">
                        <p class="announcement-text">Entorpecente!</p>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer announcement-bottom">
                    <div class="row">
                        <div class="col-xs-6">
                            Complete Orders
                        </div>
                        <div class="col-xs-6 text-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div><!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Gráfico estatístico</h3>
            </div>
            <div class="panel-body">
               <label for="inputCrimes" class="col-lg-1 col-md-1">Crime*:</label>
    <div class="col-lg-3  col-md-3">
        <?php
        // renderiza html input
        echo $this->formSelect($formRelarorio->get('id_crimeG'));
        // renderiza elemento de erro
        echo $this->formElementErrors()
                ->setMessageOpenFormat('<small class="text-danger">')
                ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                ->setMessageCloseString('</small>')
                ->render($formRelarorio->get('id_crimeR'));
        ?>
        <br>
    </div>
       <div class="box-chart">
        <canvas id="GraficoBarra" style="width:100%;"></canvas>
    </div>
    <label for="inputDataI" class="col-lg-1 col-md-1 ">Data/hora Início*:</label>
    <div class="col-lg-3  col-md-3">
        <div class='input-group date' id='datetimepickerF'>
            <?php
            // renderiza html input
            echo $this->formInput($formRelarorio->get('dataiG'));
            // renderiza elemento de erro
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formRelarorio->get('datai'));
            ?>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
        <br>
    </div>

    <label for="inputDataF" class="col-lg-1 col-md-1 ">Data/hora Fim*:</label>
    <div class="col-lg-3  col-md-3">
        <div class='input-group date' id='datetimepickerI'>
            <?php
            // renderiza html input
            echo $this->formInput($formRelarorio->get('datafG'));
            // renderiza elemento de erro
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formRelarorio->get('dataf'));
            ?>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
        <br>
       
    </div>
     <button type="button" id="btnGrafico" class="btn btn-primary fa fa-bar-chart-o "> Gráfico</button>
</div>
 
            </div>
        </div>
</div><!-- /.row -->
