<div class="topo-table">
    <div class="row">
        <div class="col-lg-12">
            <br/>
            <h2>Endereços</h2>
            <ol class="breadcrumb">
                <li class="active"><i class="fa fa-dashboard"></i> Controle dos Endereços</li>
            </ol>
        </div>
    </div>
    
    <div class="btn-group" title="Quantidades por Página">
        <button type="button" class="btn btn-default"><?php echo $this->itens_pagina; ?></button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right" style="min-width: 75px" role="menu">
            <?php foreach (['005', '010', '025', '050', '100'] as $value): ?>
                <li class="<?php echo ($this->itens_pagina == $value ? 'active' : ''); ?>"><a href="<?php echo $this->url('endereco', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_end' => $coluna_end, 'coluna_sort' => $this->coluna_sort, 'itens_pagina' => $value, 'search' => $this->search]]) ?>"><?php echo $value; ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <form class="form-inline pull-right" role="form">
        <div class="btn-group">
            <label class="sr-only" for="localizar">Buscar...</label>
            <input type="search" name="search" value="<?php echo $this->search; ?>" class="form-control" id="localizar" placeholder="Bucar...">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
    </form>
</div>

<br />
<br />

<div class="col-lg-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="glyphicon glyphicon-home"></i> Endereços</h3>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped tablesorter">
                    <thead>
                        <!--pega o cabeçalho da tabela em partial/colunas_sort -->
                        <?php echo $this->partial('partial/endereco/colunas_sort'); ?>
                    </thead>
                    <tbody>
                        <?php foreach ($this->endereco as $i => $endereco): ?>
                            <tr>
                                <td class="text-center"><?php echo $endereco->getId_end(); ?></td>
                                <td class="text-center"><?php echo $endereco->getRua(); ?></td>
                                <td class="text-center"><?php echo $endereco->getNumero(); ?></td>
                                <td class="text-center"><?php echo $endereco->getId_bai()->getBairro() ?></td>
                                <td class="text-center"><?php echo $endereco->getMunicipio()->getMunicipio()?></td>
                                
                            </tr>  
                        <?php endforeach; ?>
                    </tbody>
                </table>

            </div>
            <?php
// controle de paginação
            echo $this->paginationControl(
                    // objeto contentdo os vtr
                    $this->endereco,
                    // tipo de style da paginação
                    'Sliding',
                    // partial que vai conter o html da paginação
                    [/* path */ 'partial/endereco/paginator.phtml', /* modulo */ 'Application'],
                    // link rotas da paginação
                    ['route' => 'endereco']
            );
            ?>
        </div>
    </div>
</div>
<div class="header">
    <ul class="nav nav-pills pull-left">
        <?php
        $voltar = $this->url('config');
        ?>
        <li <?php echo $this->menuAtivo($voltar); ?>>
            <a href="<?php echo $voltar; ?>">voltar</a>
        </li>
    </ul>
</div>
